Music
anbehindY/Ruby-capstone pull request #17
Opened 2023-07-13 07:52 UTC by Daniel-Kigozi

I implemented the following
- Implemented the music album 
- Implemented the genre

2023-07-13 08:44 UTC, osmanwako commented on classes/musicAlbum.rb
> +  def initialize(on_spotify:, **attributes)
from given design we have **attribute** propertie can your replace with publish_date

2023-07-13 08:48 UTC, osmanwako commented on classes/musicAlbum.rb
> +    super(attributes)
Since we have to pass the publish_date parameter to super  Items class change attribute with publish_date

2023-07-13 08:52 UTC, osmanwako commented on modules/music_module.rb
> +        @m_source = gets.chomp
From the given diagram We do not have to implement a source class would you remove the source attribute

2023-07-13 08:59 UTC, osmanwako requested changes
Hello @Daniel-Kigozi

2023-07-14 08:16 UTC, anbehindY approved these changes
Hi @Daniel-Kigozi  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/74744787/224142346-a8961d25-362d-4385-a9ca-c531ce5acd04.png)

## Highlights 

- no linter errors 💯 
- Great implementatin of methods ✅ 

Cheers and Happy coding!👏👏👏


------

2023-07-14 08:19 UTC, merged